spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    
security:
  max-login-attempts: 10
  access-token-minutes: 15
  refresh-token-days: 1
  absolute-session-days: 7
  secret-key: ${JWT_SECRET:ESTA_ES_UNA_CLAVE_SUPER_SEGURA_MINIMO_256_BITS_CAMBIAR_EN_PRODUCCION_123456}